# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 02:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import online_course.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
                ('cover', models.ImageField(null=True, upload_to=online_course.utils.uploaded_filename, validators=[online_course.utils.validate_file_extension])),
                ('students', models.ManyToManyField(related_name='courses_learning', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_teaching', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
