# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('s', '学生'), ('t', '教师')], max_length=1)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('m', '男'), ('f', '女')], max_length=1)),
                ('company', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=10000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
