# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 14:24
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to=account.models.uploaded_filename, validators=[account.models.validate_file_extension]),
        ),
    ]
