site_name: 开发文档

# Repository
repo_name: HIT-Go-Forward/Online-Course-Sharing-Platform
repo_url: https://github.com/HIT-Go-Forward/Online-Course-Sharing-Platform
edit_uri: ""

# Configuration
theme:
  name: null
  custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: 'zh'
  direction: ltr
  feature:
    tabs: false
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"
    
# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/HIT-Go-Forward/Online-Course-Sharing-Platform

# Extensions
markdown_extensions:
  - markdown.extensions.codehilite:
  - markdown.extensions.admonition
  - markdown.extensions.toc:
      permalink: true
    
# Page tree
pages:
  - 关于: index.md
  - 术语表: 术语表.md
  - 页面文档:
    - 首页: 页面文档/首页.md
    - 用户相关: 页面文档/用户相关.md
    - 课程相关: 页面文档/课程相关.md
  - 杂项: 杂项.md

